# ClusterRoleBinding: gán ClusterRole "cluster-read-only" cho ServiceAccount "cluster-reader" trong namespace default
# Quyền áp dụng TOÀN CLUSTER (đọc pods, nodes, PV ở mọi namespace)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-read-only-binding
subjects:
  - kind: ServiceAccount
    name: cluster-reader
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-read-only
  apiGroup: rbac.authorization.k8s.io
