# RoleBinding: gán Role "read-only" cho ServiceAccount "reader" trong namespace default
# SA "reader" phải tồn tại: kubectl create serviceaccount reader -n default
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-only-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: reader
    namespace: default
roleRef:
  kind: Role
  name: read-only
  apiGroup: rbac.authorization.k8s.io
