# Pod với đủ 3 probe: startup, liveness, readiness
# Dùng khi app khởi động chậm (startupProbe pass xong mới chạy liveness/readiness)
apiVersion: v1
kind: Pod
metadata:
  name: nginx-startup-probe
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.25-alpine
      ports:
        - containerPort: 80
      startupProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 2
        periodSeconds: 3
        failureThreshold: 30   # 30 * 3 = 90s tối đa chờ khởi động
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 0  # Chỉ chạy sau khi startupProbe pass
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 0
        periodSeconds: 5
