# Service type NodePort: truy cập từ ngoài qua <NodeIP>:<NodePort>
# Port 30000-32767; nếu không chỉ định nodePort, K8s tự gán
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080   # Tùy chọn: chỉ định port cố định (30000-32767)
