# CRD đơn giản: resource "Hello" (api.example.com/v1)
# Không có controller - chỉ lưu trong etcd. Controller thật cần code Go/Python.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hellos.example.com
spec:
  group: example.com
  names:
    kind: Hello
    listKind: HelloList
    plural: hellos
    singular: hello
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
            status:
              type: object
              properties:
                phase:
                  type: string
      subresources:
        status: {}
